### ISSUE TITLE
Rename fails with elements correctly missing an end tag

### ISSUE THREAD

**Issue by codestothestars** [krizzdewizz/vscode-tag-rename#1]
tag-rename 0.1.0

When an element's end tag is missing, attempting to rename it or any of its ancestors results in an error.

Take this example:
```html
<section>
    <div class='foo'>
        <div class='bar'>
            <span></span>
            <input>
            <span></span>
        </div>
    </div>
</section>
```

Note that the `input` does not have an end tag. This is valid HTML5. Attempting to rename it, the `section`, or the `div.foo` results in an error message `No result`. Attempting to rename the `div.bar` renames the opening tag correctly, but renames the closing tag of `div.foo` instead of the closing tag of `div.bar`.

Fortunately this does not affect the element's siblings. Renaming either of the `span` elements still works correctly.

**Comment by krizzdewizz** [comment]
Thanks for your investigations and narrowing down the problem. I'll fix that soon,

**Comment by krizzdewizz** [comment]
The new version 0.1.1 now handles self-closing and HTML void elements.

**Comment by codestothestars** [comment]
Nice, already got the update and it's working splendidly. Thank you!

**Comment by krizzdewizz** [comment]
Cool. Thanks for testing!
