### ISSUE TITLE
Allow renaming in PHP files

### ISSUE THREAD

**Issue by codestothestars** [krizzdewizz/vscode-tag-rename#2]
I don't know whether you would like to support PHP files, but if so, can you allow tag renaming for .php files? It appears that the only thing preventing this is the file extension, as I am able to rename all of the tags in the following snippet when the file extension is .html instead of .php.

```php
<?php
if ($_GET["view"] === "table") {
?>
<table>
    <?php
    foreach ($result["attributes"] as $name => $value) {
    ?>
    <tr class='attribute'><td class='name'><?=$name?>:</td> <td><?=$value?></td></tr>
    <?php
    }
    ?>
</table>
<?php
}
?>
```

**Comment by krizzdewizz** [comment]
Hi, never thought this would work ;). Surely I can add support for php, but I'd like to verify first, if it plays well with other php "Rename Providers"...do you know an extension that provides renaming of php symbols?

**Comment by codestothestars** [comment]
It appears that there are no extensions that rename PHP variables right now. A search for "php rename" in the extensions library and "vscode php rename" on Google do not yield one. There's also an [SO question](http://stackoverflow.com/questions/37523793/how-to-change-all-occurrences-of-variable-name-in-visual-studio-code-for-php) with the only answer indicating the same. The closest thing appears to be [PHP Intellisense](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense), which lists renaming as a Todo but does not give any indication of when it will be implemented.

**Comment by krizzdewizz** [comment]
Thanks for  your investigations. I've just published a new version with PHP support.

**Comment by codestothestars** [comment]
Got the update and it's working perfectly for me. Thank you!

**Comment by krizzdewizz** [comment]
You are welcome! Thanks for contributing.
