### ISSUE TITLE
.vue SFC support

### ISSUE THREAD

**Issue by rndmerle** [krizzdewizz/vscode-tag-rename#4]
Hi.

I added `"onLanguage:vue"` in your package.json, in the hope it would be enough to support the `<template>` part of a VueJS SFC file. But F2 doesn't trigger anything in those files.
Anything else would be needed?

A sample.vue:
```
<template>
    <div class="class">
        <span>Span</span>
    </div>
</template>

<script lang="ts">
</script>
```

**Comment by krizzdewizz** [comment]
In <user-dir>/.vscode/extensions/krizzdewizz.tag-rename-0.2.1/out/src/extension.js, add 'vue' to the RENAME_PROVIDERS array and restart vscode.

Also, you need at least one extension that contributes to the 'vue' language, such as 'vue-ls'.

In the next release, I'll add the vue support.

**Comment by rndmerle** [comment]
Thanks a ton :)
