### ISSUE TITLE
Twig support

### ISSUE THREAD

**Issue by uturnr** [krizzdewizz/vscode-tag-rename#6]
It would be great if this could support twig, or allow configuration for the user to specify which languages they would like to use it for.

**Comment by krizzdewizz** [comment]
Hi, sorry. I'm no longer maintaining this project. You need two things to support another language:
- In package.json, add a  "onLanguage:twig" entry to "activationEvents"
- In extension.ts, add 'twig' to the RENAME_PROVIDERS array.

These files reside in ~/.vscode/extensions/krizzdewizz.tag-rename-0.2.1

**Comment by uturnr** [comment]
Thanks!

**Comment by krizzdewizz** [comment]
You are welcome.
